checks:
  javascript: true
build:
  environment:
    node: v10.14.2
  nodes:
    analysis:
      dependencies:
        override:
          - npm install typescript
          - npx tsc --target es6 --outDir dist src/index.ts
          - ls -la dist
      tests:
        override:
          - js-scrutinizer-run --enable-security-analysis
          - eslint-run
    tests:
      dependencies:
        override:
          - npm install nyc@^15 mocha@^8 chai@^4
      tests:
        override:
          - command: npx nyc --reporter=clover mocha --recursive
            coverage:
              file: coverage/clover.xml
              format: clover
filter:
  paths:
    - lib/index.js
  excluded_paths:
    - dist/util/Ed25519.ts