checks:
  javascript: true
build:
  environment:
    node: v10.14.2
  nodes:
    analysis:
      before:
        - npx tsc --target es6 --outDir dist src/index.ts
      tests:
        override:
          - js-scrutinizer-run --enable-security-analysis
          - eslint-run
filter:
  paths:
    - dist/
  excluded_paths:
    - dist/util/Ed25519.ts