checks:
  javascript: true
build:
  environment:
    node: v10.14.2
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run --enable-security-analysis
          - eslint-run
    tests:
      dependencies:
        override:
          - npm install mocha@^8 chai@^4
      tests:
        override:
          - command: npx mocha --recursive
    coverage:
      dependencies:
        override:
          - npm install typescript@^3 nyc@^15 mocha@^8 chai@^4
      tests:
        override:
          - command: npx nyc --reporter=lcov --reporter=text mocha --recursive
            coverage:
              file: coverage/lcov.info
              format: lcov
filter:
  paths:
    - dist/
  excluded_paths:
    - dist/util/Ed25519.ts