checks:
  javascript: true
build:
  environment:
    node: v10.14.2
  nodes:
    analysis:
      dependencies:
        override:
          - echo 1
      tests:
        override:
          - js-scrutinizer-run
filter:
  paths:
    - src/
  dependency_paths:
    - src/util/Ed25519.ts