checks:
  javascript: true
build:
  environment:
    node: v10.14.2
  nodes:
    analysis:
      tests:
        before:
          - npx tsc --target es6 --outDir dist src/index.ts
        override:
          - js-scrutinizer-run
filter:
  excluded_paths:
    - lib/